# Generated by Django 4.1.13 on 2024-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=200)),
                ('Bauthor', models.CharField(max_length=200)),
                ('Bcontact', models.CharField(max_length=15)),
                ('Bprice', models.CharField(max_length=8)),
                ('Breleasedate', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
