# Generated by Django 4.1.13 on 2024-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Breleasedate',
            field=models.DateField(),
        ),
    ]
