# Generated by Django 4.1.13 on 2024-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Iid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Iname', models.CharField(max_length=200)),
                ('Idetail', models.CharField(max_length=15)),
                ('Istock', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
