# Generated by Django 4.1.13 on 2024-03-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Idetail',
            new_name='Iprice',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Istock',
            new_name='Iquantity',
        ),
    ]
