# Generated by Django 4.1.13 on 2024-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_idetail_inventory_iprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Iprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Iquantity',
            field=models.PositiveIntegerField(),
        ),
    ]
