# Generated by Django 4.1.13 on 2024-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Mname', models.CharField(max_length=20, verbose_name='电影名称')),
                ('Mdirector', models.CharField(max_length=20)),
                ('Mreleased_date', models.DateField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
