# Generated by Django 4.1.13 on 2024-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sname', models.CharField(max_length=10)),
                ('Sroll_num', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Scourse', models.CharField(max_length=20)),
                ('Sstandard', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
