# Generated by Django 4.1.13 on 2024-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=200)),
                ('Elocation', models.CharField(max_length=50)),
                ('Eprice', models.CharField(max_length=30)),
                ('Econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
